name: deploy_workflow
on: 
    pull_request:
        types:
            - opened
    workflow_dispatch:
    push:
jobs:
    test:

        runs-on: ubuntu-latest
        steps:

            - name: get_code
              uses: actions/checkout@v4

            - name: install_nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: install_dependencies
              run: npm ci

            - name: run_test
              run: npm test
    build:

      runs-on: ubuntu-latest
      steps:

        - name: get_code
          uses: actions/checkout@v4

        - name: install_nodejs
          uses: actions/setup-node@v4
          with:
            node-version: 18   
        
        - name: install_dependencies
          run: npm ci

        - name: build_website
          run: npm run build

        - name: upload_artifacts
          uses: actions/upload-artifact@v3
          with:
            name: src-file
            path: src

    deployment:

        runs-on: ubuntu-latest
        steps:

            - name: get_code
              uses: actions/checkout@v4

            - name: install_nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: install_dependencies
              run: npm ci

            - name: build_project
              run: npm run build

    output_context:
        runs-on: ubuntu-latest
        steps:
            - name: work_on_githubaction_context
              run: echo "${{ toJson(github) }}"
            