name: deploy_workflow
on: 
    pull_request:
        types:
            - opened
    workflow_dispatch:
jobs:
    test:

        runs-on: ubuntu-latest
        steps:

            - name: get_code
              uses: actions/checkout@v4

            - name: install_nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: install_dependencies
              run: npm ci

            - name: run_test
              run: npm test

    deployment:

        runs-on: ubuntu-latest
        steps:

            - name: get_code
              uses: actions/checkout@v4

            - name: install_nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: install_dependencies
              run: npm ci

            - name: build_project
              run: npm run build

    output_context:
        runs-on: ubuntu-latest
        steps:
            - name: work_on_githubaction_context
              run: echo "${{ toJson(github) }}"
            