name: deploy_workflow
on: 
    pull_request:
        types:
            - opened
    workflow_dispatch:
    push:
      branches:
        - main
jobs:
    test:

        runs-on: ubuntu-latest
        steps:

            - name: get_code
              uses: actions/checkout@v4

            - name: install_nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: install_dependencies
              run: npm ci

            - name: run_test
              run: npm test
    build:
      needs: test
      runs-on: ubuntu-latest
      steps:

        - name: get_code
          uses: actions/checkout@v4

        - name: install_nodejs
          uses: actions/setup-node@v4
          with:
            node-version: 18   
        
        - name: install_dependencies
          run: npm ci

        - name: build_website
          run: npm run build

        # - name: upload_artifacts
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: dist-folder
        #     path: dist

        - name: upload_to_azure_storage_account
          env:
            AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
            AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
            AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}          
          uses: azure/cli@v2
          with:
            azcliversion: latest

            inlineScript: |
              az storage blob upload-batch \
              --account-name "$AZURE_STORAGE_ACCOUNT" \
              --sas-token "$AZURE_STORAGE_SAS_TOKEN" \
              --destination "$AZURE_CONTAINER_NAME" \
              --source ./dist \
              --destination-path dist-folder
            
      

    deployment:

        needs: build
        runs-on: ubuntu-latest
        steps:

          # - name: download_artifacts
          #   uses: actions/download-artifact@v4
          #   with:
          #     name: dist-folder
          
          - name: download_artifact_from_azure_storage
            uses: azure/cli@v2
            env:
              AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
              AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
              AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
            with:
              azcliversion: latest
              inlineScript: |
                mkdir -p download-dist
                az storage blob download-batch \
                --account-name "$AZURE_STORAGE_ACCOUNT" \
                --sas-token "$AZURE_STORAGE_SAS_TOKEN" \
                --destination ./download-dist \
                --source "$AZURE_CONTAINER_NAME" \
                --pattern "dist-folder/*"



          - name: Test_folders
            run: |
              pwd
              whoami
              ls -l | grep download-dist
              ls -l download-dist/
              cd download-dist/
              pwd 
              ls -l 
              cd dist-folder
              ls -l

    output_context:
        runs-on: ubuntu-latest
        steps:
            - name: work_on_githubaction_context
              run: echo "${{ toJson(github) }}"
            